/** @type {import('tailwindcss').Config} */
export default {
  content: [],
  theme: {
    extend: {
      colors: {
        surface: "#faf9fd",
        "surface-dim": "#dad9dd",
        "surface-bright": "#faf9fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f7",
        "surface-container": "#efedf1",
        "surface-container-high": "#e9e7eb",
        "surface-container-highest": "#e3e2e6",
        "on-surface": "#1a1c1e",
        "on-surface-variant": "#43474e",
        "inverse-surface": "#2f3033",
        "inverse-on-surface": "#f1f0f4",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        primary: "#002045",
        "on-primary": "#ffffff",
        "primary-container": "#1a365d",
        "on-primary-container": "#86a0cd",
        "inverse-primary": "#adc7f7",
        secondary: "#0061a5",
        "on-secondary": "#ffffff",
        "secondary-container": "#66affe",
        "on-secondary-container": "#004172",
        tertiary: "#321b00",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#4f2e00",
        "on-tertiary-container": "#c6955e",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        background: "#faf9fd",
        "on-background": "#1a1c1e",
        "surface-variant": "#e3e2e6",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
      },
      fontSize: {
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" },
        ],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "1.1", letterSpacing: "-0.03em", fontWeight: "800" },
        ],
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-md": [
          "24px",
          { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" },
        ],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "600" },
        ],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "12px",
        md: "24px",
        lg: "48px",
        xl: "80px",
        gutter: "24px",
        margin: "32px",
      },
      boxShadow: {
        "layer-1": "0 2px 8px 0 rgba(0,0,0,0.04)",
        "layer-2": "0 4px 12px 0 rgba(0,0,0,0.08)",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
