export const ICONS = [
  { label: "Dashboard", value: "lucide:layout-dashboard" },
  { label: "Home", value: "lucide:home" },
  { label: "Menu", value: "lucide:menu" },
  { label: "Grid", value: "lucide:layout-grid" },
  { label: "Layers", value: "lucide:layers" },
  { label: "Folder", value: "lucide:folder" },
  { label: "Folder Terbuka", value: "lucide:folder-open" },
  { label: "File", value: "lucide:file" },
  { label: "Dokumen", value: "lucide:file-text" },
  { label: "Gambar", value: "lucide:image" },
  { label: "Galeri", value: "lucide:images" },
  { label: "Video", value: "lucide:video" },
  { label: "Post", value: "lucide:postpaper" },
  { label: "Pengumuman", value: "lucide:megaphone" },
  { label: "Lonceng", value: "lucide:bell" },
  { label: "Kalender", value: "lucide:calendar" },
  { label: "Jam", value: "lucide:clock" },
  { label: "Pengguna", value: "lucide:user" },
  { label: "Pengguna Grup", value: "lucide:users" },
  { label: "Admin/Shield", value: "lucide:shield" },
  { label: "Kunci", value: "lucide:lock" },
  { label: "Pengaturan", value: "lucide:settings" },
  { label: "Alat", value: "lucide:wrench" },
  { label: "Tautan", value: "lucide:link" },
  { label: "Tautan Eksternal", value: "lucide:external-link" },
  { label: "Grafik", value: "lucide:bar-chart-3" },
  { label: "Statistik", value: "lucide:trending-up" },
  { label: "Mail/Pesan", value: "lucide:mail" },
  { label: "Chat", value: "lucide:message-square" },
  { label: "Info", value: "lucide:info" },
  { label: "Bantuan", value: "lucide:help-circle" },
  { label: "Bintang", value: "lucide:star" },
  { label: "Hati", value: "lucide:heart" },
  { label: "Tag", value: "lucide:tag" },
  { label: "Kategori", value: "lucide:list-tree" },
  { label: "Filter", value: "lucide:filter" },
  { label: "Cari", value: "lucide:search" },
  { label: "Plus/Tambah", value: "lucide:plus" },
  { label: "Edit", value: "lucide:pencil" },
  { label: "Hapus", value: "lucide:trash-2" },
  { label: "Unduh", value: "lucide:download" },
  { label: "Unggah", value: "lucide:upload" },
  { label: "Refresh", value: "lucide:refresh-cw" },
  { label: "Print", value: "lucide:printer" },
  { label: "Lokasi", value: "lucide:map-pin" },
  { label: "Peta", value: "lucide:map" },
  { label: "Gedung/Kampus", value: "lucide:building-2" },
  { label: "Sekolah", value: "lucide:graduation-cap" },
  { label: "Buku", value: "lucide:book-open" },
  { label: "Perpustakaan", value: "lucide:library" },
  { label: "Piala/Prestasi", value: "lucide:trophy" },
  { label: "Sertifikat", value: "lucide:award" },
  { label: "Struktur Organisasi", value: "lucide:sitemap" },
  { label: "Kontak", value: "lucide:phone" },
  { label: "Amplop", value: "lucide:mail-open" },
  { label: "Sosial Media", value: "lucide:share-2" },
  { label: "Facebook", value: "lucide:facebook" },
  { label: "Instagram", value: "lucide:instagram" },
  { label: "Twitter/X", value: "lucide:twitter" },
  { label: "Youtube", value: "lucide:youtube" },
  { label: "Linkedin", value: "lucide:linkedin" },
  { label: "Github", value: "lucide:github" },
  { label: "Globe/Website", value: "lucide:globe" },
  { label: "Database", value: "lucide:database" },
  { label: "Server", value: "lucide:server" },
  { label: "Kode", value: "lucide:code" },
  { label: "Terminal", value: "lucide:terminal" },
] as const;

export type IconOption = (typeof ICONS)[number];

export type Icon = IconOption["value"];
export type IconLabel = IconOption["label"];
